version: '3.8'

services:

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    networks:
      - db-network
    environment:
      MYSQL_DATABASE: permApp
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - ./src/main/sql/permApp.sql:/docker-entrypoint-initdb.d/permApp.sql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8000:80
    links:
     - db:mysql
    networks:
      - db-network
    environment:
      MYSQL_ROOT_PASSWORD: toor
      PMA_HOST: db
    depends_on:
      - db
  
  web:
    image: tomcat:9.0
    container_name: tomcat
    restart: always
    links:
      - db:mysql
      - db:jdbc
      - db:localhost
    networks:
      - db-network
    ports:
        - 8080:8080
    depends_on:
      - db
    volumes:
        - ./target/permApp-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/permApp.war
    environment:
      - TOMCAT_USERNAME=root
      - TOMCAT_PASSWORD=password
    
networks:
  db-network: